# CIANCHOSAINT new-build: PDF reference search FunctionTool.
#
# Per the openspec/changes/cianchosaint-pdf-reference-integration-v1/
# specs/cianchosaint-pdf-reference/spec.md, Requirement: The PDF
# reference search FunctionTool that the AG-UI chat window can
# invoke to query the BAML-extracted PDF content.
#
# Wholesale file:
#   hmgcc/a176bba9_de078709_1777299087.pdf
#   (HMGCC Co-Creation Challenge Form, OFFICIAL classification,
#   MSIP_Label_d8a60473-494b-4586-a1bb-b0e663054676).
#
# The FunctionTool searches the pre-extracted PDF reference content
# at dlt_sources/cianchosaint/uk/intelligence_agencies/hmgcc_pdf_reference.json
# (regenerated by the mise task `cianchosaint:pdf-reference:extract`).
#
# Licence: BUSL-1.1 (per LICENSE.md)
#
# Conservative posture: this tool NEVER transmits the PDF or its
# extracted content to a remote server. All queries are local. The
# OSINT ceiling + the licence posture apply (the PDF is used as a
# REFERENCE DOC ONLY — not as an OSINT feed).

"""cianchosaint.cianchosaint.tools.pdf_reference_search — PDF reference search FunctionTool.

Cross-references:
- `hmgcc/a176bba9_de078709_1777299087.pdf` (the wholesale PDF)
- `baml_client.b.ExtractPDFReference(pdf_text)` (BAML extraction)
- `baml_client.b.ExtractPDFReference.json` (cached extraction)
- `docs/source-catalogue/17-uk-hmgcc-pdf-reference.md` (the
  canonical doc)

Returns a typed search-result dict for analyst review ONLY.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from google.adk.tools import FunctionTool

logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------------
# Paths (overrideable via env for tests)
# -----------------------------------------------------------------------------
REPO_ROOT = Path(
    os.environ.get(
        "CIANCHOSAINT_REPO_ROOT",
        Path(__file__).resolve().parents[3],
    )
).resolve()
PDF_PATH = REPO_ROOT / "hmgcc" / "a176bba9_de078709_1777299087.pdf"
EXTRACTED_JSON_PATH = (
    REPO_ROOT
    / "dlt_sources"
    / "cianchosaint"
    / "uk"
    / "intelligence_agencies"
    / "hmgcc_pdf_reference.json"
)
CACHE_PATH = (
    REPO_ROOT
    / "stedding"
    / "pdf_reference_cache"
    / "a176bba9_de078709_1777299087.json"
)


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
def _pdf_to_text(pdf_path: Path) -> str:
    """Extract the plain text from a PDF via the `pdftotext` CLI.

    Returns an empty string if the binary is missing or the PDF is
    unreadable. Conservative posture: never raise — the caller falls
    back to "no content available".
    """
    if not pdf_path.exists():
        logger.warning(
            "pdf_reference_search: PDF not found at %s", pdf_path,
        )
        return ""
    try:
        proc = subprocess.run(
            ["pdftotext", str(pdf_path), "-"],
            check=True,
            capture_output=True,
            text=True,
            timeout=60,
        )
        return proc.stdout
    except FileNotFoundError:
        logger.warning(
            "pdf_reference_search: pdftotext not on PATH — cannot re-extract the PDF"
        )
        return ""
    except subprocess.TimeoutExpired:
        logger.error("pdf_reference_search: pdftotext timed out after 60s")
        return ""
    except subprocess.CalledProcessError as exc:
        logger.error("pdf_reference_search: pdftotext exited %d", exc.returncode)
        return ""


def _load_extraction_cache() -> dict[str, Any] | None:
    """Load the cached BAML-extracted PDFReference record."""
    path = EXTRACTED_JSON_PATH if EXTRACTED_JSON_PATH.exists() else CACHE_PATH
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        logger.error("pdf_reference_search: extraction cache corrupted: %s", exc)
        return None


def _score_keyword_match(text: str, query: str) -> list[str]:
    """Return the lines that mention any keyword in the query.

    Cheap & conservative: case-insensitive substring match against
    each whitespace-separated keyword in the query. No fuzzy
    matching, no LLM re-ranking — analyst reads the hits.
    """
    keywords = [kw.strip().lower() for kw in query.split() if len(kw.strip()) >= 3]
    if not keywords:
        return []
    hits: list[str] = []
    for line in text.splitlines():
        line_lc = line.lower()
        if any(kw in line_lc for kw in keywords):
            hits.append(line.strip())
    # Cap the hits — analysts read at most 20 lines per query.
    return hits[:20]


# -----------------------------------------------------------------------------
# Public FunctionTool
# -----------------------------------------------------------------------------
async def pdf_reference_search(
    query: str,
    max_results: int = 10,
) -> dict[str, Any]:
    """Search the extracted content of the HMGCC Co-Creation wargaming
    challenge brief PDF.

    Args:
        query: The natural-language search query (e.g. "TRL
            requirements", "minimum TRL", "Cyber Essentials",
            "HMGCC Co-Creation", "Bluetooth", "12-hour").
        max_results: Maximum number of matched lines to return
            (default 10, capped at 20).

    Returns:
        A typed dict with the 7 canonical fields:
        query, pdf_title, pdf_topic, msip_label,
        classification_banner, matched_lines, total_lines_scanned,
        last_extracted, osint_ceiling_enforced, licence_posture,
        analyst_review_required.

    Reference:
        - Wholesale PDF:
          hmgcc/a176bba9_de078709_1777299087.pdf
        - Canonical doc:
          docs/source-catalogue/17-uk-hmgcc-pdf-reference.md
        - BAML extraction:
          baml_src/cianchosaint/processing/pdf_reference_extraction.baml
    """
    logger.info(
        "pdf_reference_search",
        extra={"query": query, "max_results": max_results},
    )

    # 1. Load the cached BAML extraction (PDFReference).
    extraction = _load_extraction_cache() or {}
    pdf_title = extraction.get("title", "Unknown")
    pdf_topic = extraction.get("topic", "")
    msip_label = extraction.get("msip_label")
    classification_banner = extraction.get("classification_banner")
    last_extracted = extraction.get("last_verified") or datetime.now(timezone.utc).isoformat()

    # 2. Re-extract the PDF text on demand if the cache is missing.
    pdf_text = _pdf_to_text(PDF_PATH)
    if not pdf_text:
        # Fall back to the key_points list (which IS cached).
        pdf_text = "\n".join(extraction.get("key_points", []) or [])

    matched = _score_keyword_match(pdf_text, query)
    if max_results and max_results > 0:
        matched = matched[:max_results]

    return {
        "query": query,
        "pdf_title": pdf_title,
        "pdf_topic": pdf_topic,
        "msip_label": msip_label,
        "classification_banner": classification_banner,
        "matched_lines": matched,
        "total_lines_scanned": pdf_text.count("\n") + 1 if pdf_text else 0,
        "last_extracted": last_extracted,
        "osint_ceiling_enforced": True,
        "licence_posture": "BUSL-1.1 v2 (British-Isles-only)",
        "analyst_review_required": True,
    }


pdf_reference_search_tool = FunctionTool(func=pdf_reference_search)


__all__ = [
    "pdf_reference_search",
    "pdf_reference_search_tool",
]
